### ISSUE TITLE
UI package rebuild doesn't trigger remix rebuild

### ISSUE THREAD

**Issue by kennethvdberghe** [bronifty/turbo-remix#1]
**Reproduction:**
- `npm run dev`
- open `localhost:3000` to show running remix app
- make a change in `Button.tsx` in `packages/ui`
- changes are not being shown
- make a change in remix app to trigger rebuild
- changes from button are shown

**Wanted:**
Is there a way to make the changes of the Button appear without triggering remix build manually?

Thanks!

**Comment by kennethvdberghe** [comment]
Problem seems to be only in the remix app, the nextjs app (I guess because of `next-transpile-modules`) does get triggered after ui built 😞

**Comment by bronifty** [comment]
@kennethvdberghe  good catch. i have asked the maintainers of remix if they have an ootb solution but the plugin modules approach may be something to look into on this one cf https://github.com/kentcdodds/babel-plugin-macros

**Comment by JannikWempe** [comment]
Are there any solutions to that?

Other than that this setup works great 👍

**Comment by bronifty** [comment]
> Are there any solutions to that?
> 
> Other than that this setup works great 👍

this solution was a total hack job but yes i think it works ok. The maintainers of remix have informed me that the plugin modules approach is not an option. And they actually have a turbo repo for remix on their site. I would highly recommend checking it out as I won't be maintaining this at all. thanks
